### ISSUE TITLE
Followup call from TPAC

### ISSUE THREAD

**Issue by yoavweiss** [WICG/address-autofill#3]
As a followup from our [TPAC conversation](https://gist.github.com/yoavweiss/b919e665ff91a047cbef3ea9ae7f01ba), I think it'd be good for us to get together, zoom in on the problem, and hash out a solution together.

Talking to @martinLechnerShopify, he graciously agreed to lead those discussions.

If you're interested in joining, please mark your [availability](https://doodle.com/meeting/participate/id/eXnB6zAb) and we'll schedule something based off of that. Also - feel free to let interested folks know.

/cc @annevk @battre @rsolomakhin @galich @stephenmcgruer @nicksteele @schwering

**Comment by rsolomakhin** [comment]
Thank you for settings this up! I've marked my availability as requested.

**Comment by nicksteele** [comment]
Marked my availability as well, looking forward to chatting!

**Comment by yoavweiss** [comment]
OK, so it looks like there's no slot that works for everyone, but the closest we get is Thursday October 17th, 3pm CET/9am ET/6am PT.

I'll send out invites.

**Comment by martinLechnerShopify** [comment]
@yoavweiss thanks for setting this up, I assume this can be closed by now?

**Comment by yoavweiss** [comment]
Yup! But if anyone else is interested in an invite, hit me up with your email!

**Comment by annevk** [comment]
Were any notes taken?

**Comment by yoavweiss** [comment]
Thanks for the reminder - notes are at https://gist.github.com/yoavweiss/66fa988fc8a9dac3fd192048c8ef9882
