### ISSUE TITLE
Standardization of address fields

### ISSUE THREAD

**Issue by martinLechnerShopify** [WICG/address-autofill#5]
Depending on the outcome of https://github.com/WICG/address-autofill/issues/4, if we go with 1-step autofill, we will need to standardize the address fields.

**Comment by rsolomakhin** [comment]
What are the requirements for address fields in this project?

Is it possible to re-use any of the existing formats that have been researched and developed before?

The `<input>` field's `autocomplete` attribute uses https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute.

Payment Request and Contact Picker APIs use https://www.w3.org/TR/contact-picker/#infrastructure-physical-address. (This is the same format as https://github.com/google/libaddressinput.)

If these two formats do not 100% satisfy the requirements, it is preferable to make improvements to one of the existing formats and then reuse them in this project.

/cc @battre

**Comment by martinLechnerShopify** [comment]
As we have settled for a [2-step autofill approach](https://github.com/WICG/address-autofill/issues/4#issuecomment-2467908927), we won't need to standardize address fields anymore, and can rely on existing autofill tokens.
